return {
    Tag = "LobbyFan",
    Tiers = {
        High = {
            radius = 260,
            frustum = true,
            maxFans = 24,
            nearStep = 1,
            farStep = 2,
            nearFraction = 0.45,
        },
        Medium = {
            radius = 190,
            frustum = true,
            maxFans = 18,
            nearStep = 2,
            farStep = 3,
            nearFraction = 0.45,
        },
        Low = {
            radius = 140,
            frustum = true,
            maxFans = 12,
            nearStep = 3,
            farStep = 4,
            nearFraction = 0.45,
        },
    },
    Groups = {
        {
            id = "rangeCeiling",
            modelName = "fan",
            rotor = "fan",
            axis = "Y",
            rpm = 42,
            direction = 1,
            rpmJitter = 0.08,
            maxFrameStep = 4,
            wobble = 0,
            path = {"range", "structure", "ceiling"},
        },
        {
            id = "tradingPlazaCeiling",
            containerName = "ceiling",
            modelName = "fan",
            rotor = "Meshes/fan (2)",
            axis = "Y",
            rpm = 88,
            direction = 1,
            rpmJitter = 0.08,
            maxFrameStep = 3,
            wobble = 0,
            path = {"tradingPlaza", "structure"},
        },
        {
            id = "armoryCeiling",
            modelName = "fan",
            rotor = "Meshes/fan (3)",
            axis = "Y",
            rpm = 104,
            direction = -1,
            rpmJitter = 0.08,
            maxFrameStep = 2,
            wobble = 0,
            detachRotorLights = true,
            lightHost = "Meshes/fanBearing (4)",
            path = {"armory", "structure", "largeCeiling"},
        },
    },
}