local v1 = {
    Damage = 20,
    Multipliers = {Arms = 1, Torso = 1, Legs = 1, Head = 1.5},
    Penetration = 1,
    PenetrationReduction = 0.5,
    MaxEnemiesPerSwing = 3,
    MaxHitsPerEnemy = 3,
    StaminaRequired = 3,
    StaminaUsed = 3,
    DelayPerShot = 0.8,
    HeavyDelayPerShot = 1.5,
    SwingStart = 0.1,
    SwingEnd = 0.3,
    SwingComboEnd = 3.5,
    HeavyStaminaRequired = 8,
    HeavyStaminaCost = 8,
    HeavySwingStart = 0.3,
    HeavySwingEnd = 1,
    HeavyChargeStaminaDrain = 0,
    ChargeTime = 0.5,
    BlockStaminaUse = 2,
    BlockStaminaDrain = 0.05,
    BlockCooldown = 0.25,
    ParryWindow = 0.25,
    BlockReduction = 0.5,
    ADSSpeed = 1,
    DrawSpeed = 2,
    HolsterSpeed = 2,
    IsMelee = true,
    UseBlockAnimation = true,
    HitRegLeniency = 10,
    SwingData = {
        Swing1 = {
            start = 0.2,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 8,
            min_dist = 8,
            yaw = -70,
            pitch = 0,
            direction = -1,
        },
        Swing2 = {
            start = 0.2,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 8,
            min_dist = 8,
            yaw = 70,
            pitch = 0,
            direction = -1,
        },
        HeavySwing = {
            start = 0.3,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 8,
            min_dist = 8,
            yaw = -70,
            pitch = 70,
            direction = -1,
        },
        HeavySwing2 = {
            start = 0.3,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 8,
            min_dist = 8,
            yaw = 70,
            pitch = 70,
            direction = -1,
        },
    },
    EquippedWalkspeedChange = 0,
    HolsteredWalkspeedChange = 0,
    EquippedWalkspeedMultiplier = 1,
    HolsteredWalkspeedMultiplier = 1,
    FirstDrawAnimation = nil,
    FirstDrawAnimationTime = nil,
    DrawAnimation = nil,
    DrawAnimationTime = nil,
    KeyFrameSounds = {
        Slash = {SoundId = "8880136011", Volume = 0.5},
        Swing = {SoundId = "6241709963", Volume = 0.5},
        HeavySwing = {SoundId = "7171591581", Volume = 0.5},
        Charge = {SoundId = "9125407249", Volume = 0.5},
    },
    UnequipSFX = {SoundId = "481731911", Volume = 0.5},
    DeploySFX = {SoundId = "5752235534", Volume = 0.5},
    HitSFX = {ID = "566593606", PlaybackSpeed = 0.8, Volume = 0.75},
    BlockSFX = {SoundId = "9125670740", Volume = 0.5},
    StartBlockSFX = {SoundId = "9116844753", Volume = 0.5},
    NewSkinsSystem = false,
    NewSkinsSystemBlacklist = {},
    WorldScaleValue = 0.81,
    Parried = function(p1) -- Line: 184
        local Parry = p1.Viewmodel.Model.KeyParts.Parry
        Parry.ParrySparks:Emit(math.random(10, 25))
        Parry.Attachment.ParryLargeSparkParticles:Emit(1)
    end,
    Blocked = function(p1) -- Line: 190
        p1.Viewmodel.Model.KeyParts.Parry.ParrySparks:Emit(math.random(10, 25))
    end,
    DynamicFOVOffsetConstant = 3,
    Offset = CFrame.new(),
    SprintOffset = CFrame.new(),
    CrouchAnimation = CFrame.new(),
    BlockOffset = CFrame.new(),
}
local v2 = CFrame.new(0, -2, 3)
v1.HolsterCF = v2 * CFrame.Angles(-0.4363323129985824, 0, 0)
v1.AttachmentNodeData = require("@game/ReplicatedStorage/common/SharedResources/Attachments/Platforms/BaseMelee")
return v1