local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Packages.Fusion)
local _ = v2.Children
local _ = v2.OnEvent
local _ = v2.peek
local v_u_3 = require("./GenericButton")
return function(p4)
	-- upvalues: (copy) v_u_3
	local v5 = p4.scope
	local v6 = p4.Text or "X"
	local v7 = p4.Font or Enum.Font.GothamBold
	local v8 = p4.TextScaled or true
	local v9 = p4.TextSize or 14
	local v10 = p4.Position or UDim2.new(0.5, 0, 0.5, 0)
	local v11 = p4.Size or UDim2.new(1, 0, 1, 0)
	local v12 = p4.AnchorPoint or Vector2.new(0.5, 0.5)
	local v13 = p4.TextColor3 or Color3.fromRGB(255, 255, 255)
	local v14 = p4.TextTransparency or 0
	local v15 = p4.TextWrapped or false
	local v16 = p4.TextXAlignment or Enum.TextXAlignment.Center
	local v17 = p4.TextYAlignment or Enum.TextYAlignment.Center
	local v18 = p4.TextTruncate or Enum.TextTruncate.None
	local v19 = p4.TextStrokeTransparency or 1
	local v20 = p4.TextStrokeColor3 or Color3.fromRGB(0, 0, 0)
	local v21 = p4.BackgroundTransparency or 1
	local v22 = p4.BackgroundColor3 or Color3.fromRGB(0, 0, 0)
	return v_u_3({
		["scope"] = nil,
		["isHovering"] = nil,
		["isHeldDown"] = nil,
		["Disabled"] = nil,
		["OnClick"] = nil,
		["Text"] = nil,
		["Font"] = nil,
		["TextScaled"] = nil,
		["TextSize"] = nil,
		["Position"] = nil,
		["Size"] = nil,
		["AnchorPoint"] = nil,
		["TextColor3"] = nil,
		["TextTransparency"] = nil,
		["TextWrapped"] = nil,
		["TextXAlignment"] = nil,
		["TextYAlignment"] = nil,
		["TextTruncate"] = nil,
		["TextStrokeTransparency"] = nil,
		["TextStrokeColor3"] = nil,
		["BackgroundTransparency"] = nil,
		["BackgroundColor3"] = nil,
		["UIAspectRatio"] = 1,
		["ZIndex"] = nil,
		["Children"] = nil,
		["scope"] = v5,
		["isHovering"] = p4.isHovering,
		["isHeldDown"] = p4.isHeldDown,
		["Disabled"] = p4.Disabled,
		["OnClick"] = p4.OnClick,
		["Text"] = v6,
		["Font"] = v7,
		["TextScaled"] = v8,
		["TextSize"] = v9,
		["Position"] = v10,
		["Size"] = v11,
		["AnchorPoint"] = v12,
		["TextColor3"] = v13,
		["TextTransparency"] = v14,
		["TextWrapped"] = v15,
		["TextXAlignment"] = v16,
		["TextYAlignment"] = v17,
		["TextTruncate"] = v18,
		["TextStrokeTransparency"] = v19,
		["TextStrokeColor3"] = v20,
		["BackgroundTransparency"] = v21,
		["BackgroundColor3"] = v22,
		["ZIndex"] = p4.ZIndex or 1,
		["Children"] = { p4.Children }
	})
end