return {
    ScreenGui = {ResetOnSpawn = false, ZIndexBehavior = Enum.ZIndexBehavior.Sibling},
    BillboardGui = {ResetOnSpawn = false, Active = true, ZIndexBehavior = Enum.ZIndexBehavior.Sibling},
    SurfaceGui = {ResetOnSpawn = false, PixelsPerStud = 50, ZIndexBehavior = Enum.ZIndexBehavior.Sibling, SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud},
    Frame = {BorderSizePixel = 0, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0)},
    ScrollingFrame = {BorderSizePixel = 0, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0), ScrollBarImageColor3 = Color3.new(0, 0, 0)},
    TextLabel = {
        BorderSizePixel = 0,
        Text = "",
        TextSize = 14,
        BackgroundColor3 = Color3.new(1, 1, 1),
        BorderColor3 = Color3.new(0, 0, 0),
        Font = Enum.Font.SourceSans,
        TextColor3 = Color3.new(0, 0, 0),
    },
    TextButton = {
        BorderSizePixel = 0,
        AutoButtonColor = false,
        Text = "",
        TextSize = 14,
        BackgroundColor3 = Color3.new(1, 1, 1),
        BorderColor3 = Color3.new(0, 0, 0),
        Font = Enum.Font.SourceSans,
        TextColor3 = Color3.new(0, 0, 0),
    },
    TextBox = {
        BorderSizePixel = 0,
        ClearTextOnFocus = false,
        Text = "",
        TextSize = 14,
        BackgroundColor3 = Color3.new(1, 1, 1),
        BorderColor3 = Color3.new(0, 0, 0),
        Font = Enum.Font.SourceSans,
        TextColor3 = Color3.new(0, 0, 0),
    },
    ImageLabel = {BorderSizePixel = 0, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0)},
    ImageButton = {BorderSizePixel = 0, AutoButtonColor = false, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0)},
    ViewportFrame = {BorderSizePixel = 0, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0)},
    VideoFrame = {BorderSizePixel = 0, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0)},
    CanvasGroup = {BorderSizePixel = 0, BackgroundColor3 = Color3.new(1, 1, 1), BorderColor3 = Color3.new(0, 0, 0)},
    SpawnLocation = {Duration = 0},
    BoxHandleAdornment = {ZIndex = 0},
    ConeHandleAdornment = {ZIndex = 0},
    CylinderHandleAdornment = {ZIndex = 0},
    ImageHandleAdornment = {ZIndex = 0},
    LineHandleAdornment = {ZIndex = 0},
    SphereHandleAdornment = {ZIndex = 0},
    WireframeHandleAdornment = {ZIndex = 0},
    Part = {
        Anchored = true,
        Size = Vector3.new(1, 1, 1),
        FrontSurface = Enum.SurfaceType.Smooth,
        BackSurface = Enum.SurfaceType.Smooth,
        LeftSurface = Enum.SurfaceType.Smooth,
        RightSurface = Enum.SurfaceType.Smooth,
        TopSurface = Enum.SurfaceType.Smooth,
        BottomSurface = Enum.SurfaceType.Smooth,
    },
    TrussPart = {
        Anchored = true,
        Size = Vector3.new(2, 2, 2),
        FrontSurface = Enum.SurfaceType.Smooth,
        BackSurface = Enum.SurfaceType.Smooth,
        LeftSurface = Enum.SurfaceType.Smooth,
        RightSurface = Enum.SurfaceType.Smooth,
        TopSurface = Enum.SurfaceType.Smooth,
        BottomSurface = Enum.SurfaceType.Smooth,
    },
    MeshPart = {
        Anchored = true,
        Size = Vector3.new(1, 1, 1),
        FrontSurface = Enum.SurfaceType.Smooth,
        BackSurface = Enum.SurfaceType.Smooth,
        LeftSurface = Enum.SurfaceType.Smooth,
        RightSurface = Enum.SurfaceType.Smooth,
        TopSurface = Enum.SurfaceType.Smooth,
        BottomSurface = Enum.SurfaceType.Smooth,
    },
    CornerWedgePart = {
        Anchored = true,
        Size = Vector3.new(1, 1, 1),
        FrontSurface = Enum.SurfaceType.Smooth,
        BackSurface = Enum.SurfaceType.Smooth,
        LeftSurface = Enum.SurfaceType.Smooth,
        RightSurface = Enum.SurfaceType.Smooth,
        TopSurface = Enum.SurfaceType.Smooth,
        BottomSurface = Enum.SurfaceType.Smooth,
    },
    VehicleSeat = {
        Anchored = true,
        Size = Vector3.new(1, 1, 1),
        FrontSurface = Enum.SurfaceType.Smooth,
        BackSurface = Enum.SurfaceType.Smooth,
        LeftSurface = Enum.SurfaceType.Smooth,
        RightSurface = Enum.SurfaceType.Smooth,
        TopSurface = Enum.SurfaceType.Smooth,
        BottomSurface = Enum.SurfaceType.Smooth,
    },
}