local v1 = {
    Damage = 20,
    Multipliers = {Arms = 1, Torso = 1, Legs = 1, Head = 1.5},
    Penetration = 1,
    PenetrationReduction = 0.5,
    MaxEnemiesPerSwing = 5,
    MaxHitsPerEnemy = 3,
    StaminaRequired = 10,
    StaminaUsed = 10,
    DelayPerShot = 0.45,
    HeavyDelayPerShot = 1.5,
    SwingStart = 0.1,
    SwingEnd = 0.3,
    SwingComboEnd = 3.5,
    OnlyDrainWhileCharging = true,
    HeavyStaminaRequired = 5,
    HeavyStaminaCost = 5,
    HeavySwingStart = 0.01,
    HeavySwingEnd = 0.5,
    HeavyChargeStaminaDrain = 0.2,
    ChargeTime = 1,
    BlockStaminaDrain = -0.05,
    BlockStaminaUse = 5,
    BlockStaminaRequired = 5,
    ParryWindow = 0.3,
    BlockReduction = 0.25,
    BlockCooldown = 0.15,
    HitEffect = "Lifesteal",
    ADSSpeed = 1,
    DrawSpeed = 1.5,
    HolsterSpeed = 1.5,
    IsMelee = true,
    HitRegLeniency = 11,
    SwingData = {
        Swing1 = {
            start = 0.2,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 10.5,
            min_dist = 8,
            yaw = -70,
            pitch = 70,
            direction = -1,
        },
        Swing2 = {
            start = 0.2,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 10.5,
            min_dist = 8,
            yaw = 70,
            pitch = 70,
            direction = -1,
        },
        HeavySwing = {
            start = 0.1,
            num_rays = 15,
            raysbeforedelay = 15,
            delaytime = 0.03,
            max_dist = 11,
            min_dist = 8,
            yaw = -70,
            pitch = 0,
            direction = -1,
            num_times = 3,
            multi_data = {
                {},
                {yaw = -70, pitch = 70},
                {yaw = 70, pitch = 70, direction = 1},
            },
        },
        HeavySwing2 = {
            start = 0.1,
            num_rays = 15,
            raysbeforedelay = 15,
            delaytime = 0.03,
            max_dist = 11,
            min_dist = 8,
            yaw = -70,
            pitch = 0,
            direction = -1,
            num_times = 3,
            multi_data = {
                {},
                {yaw = -70, pitch = 70},
                {yaw = 70, pitch = 70, direction = 1},
            },
        },
    },
    EquippedWalkspeedChange = 0,
    HolsteredWalkspeedChange = 0,
    EquippedWalkspeedMultiplier = 1,
    HolsteredWalkspeedMultiplier = 1,
    FirstDrawAnimation = nil,
    FirstDrawAnimationTime = nil,
    DrawAnimation = "Swing2",
    DrawAnimationTime = 1.5,
    KeyFrameSounds = {
        Slash = {SoundId = "8880136011", Volume = 0.5},
        Swing = {SoundId = "6241709963", Volume = 0.5},
        ChargeSlash1 = {SoundId = "8880136011", Volume = 0.5},
        ChargeSlash2 = {SoundId = "8880136011", Volume = 0.5},
        ChargeSlash3 = {SoundId = "8880136011", Volume = 0.5},
        Charge = {SoundId = "9125407249", Volume = 0.5},
    },
    UnequipSFX = {SoundId = "481731911", Volume = 0.5},
    DeploySFX = {SoundId = "5752235534", Volume = 0.5},
    HitSFX = {ID = "5989945551", PlaybackSpeed = 0.8},
    BlockSFX = {SoundId = "1194860475", Volume = 0.5},
    StartBlockSFX = {SoundId = "9116844753", Volume = 0.5},
    NewSkinsSystem = false,
    NewSkinsSystemBlacklist = {},
    Parried = function(p1) -- Line: 209
        local Parry = p1.Viewmodel.Model.KeyParts.Parry
        Parry.ParrySparks:Emit(math.random(10, 25))
        Parry.Attachment.ParryLargeSparkParticles:Emit(1)
    end,
    Blocked = function(p1) -- Line: 215
        p1.Viewmodel.Model.KeyParts.Parry.ParrySparks:Emit(math.random(10, 25))
    end,
    DynamicFOVOffsetConstant = 3,
    Offset = CFrame.new(),
    SprintOffset = CFrame.new(),
    CrouchAnimation = CFrame.new(),
}
local v2 = CFrame.new(0, -1.7, 0)
v1.BlockOffset = v2 * CFrame.Angles(1.1423973285781066, 0, -1.5707963267948966)
v2 = CFrame.new(0, -2, 3)
v1.HolsterCF = v2 * CFrame.Angles(-0.4363323129985824, 0, 0)
v1.AttachmentNodeData = require("@game/ReplicatedStorage/common/SharedResources/Attachments/Platforms/BaseMelee")
return v1