local v1 = {
    Damage = 255,
    Multipliers = {Arms = 1, Torso = 1, Legs = 1, Head = 4.7},
    Penetration = 10,
    PenetrationReduction = 1,
    MaxEnemiesPerSwing = 30,
    MaxHitsPerEnemy = 5,
    StaminaRequired = 30,
    StaminaUsed = 100,
    DelayPerShot = 2,
    HeavyDelayPerShot = 75,
    SwingStart = 0.1,
    SwingEnd = 0.3,
    SwingComboEnd = 3.5,
    HeavyStaminaRequired = 0.1,
    HeavyStaminaCost = 25,
    HeavySwingStart = 0.01,
    HeavySwingEnd = 0.5,
    HeavyChargeStaminaDrain = 0.088,
    ChargeTime = 5.8,
    BlockStaminaDrain = -0.08,
    BlockStaminaUse = 1,
    BlockStaminaRequired = 0.1,
    ParryWindow = 0.5,
    BlockReduction = 0.8,
    BlockCooldown = 0.05,
    HitEffect = "Lifesteal",
    ADSSpeed = 1,
    DrawSpeed = 0.5,
    HolsterSpeed = 0.7,
    IsMelee = true,
    HitRegLeniency = 10,
    SwingData = {
        Swing1 = {
            start = 0.2,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 1,
            min_dist = 1,
            yaw = -70,
            pitch = 70,
            direction = -1,
        },
        Swing2 = {
            start = 0.2,
            num_rays = 20,
            raysbeforedelay = 4,
            delaytime = 0.01,
            max_dist = 1,
            min_dist = 1,
            yaw = 70,
            pitch = 40,
            direction = -1,
        },
        HeavySwing = {
            start = 0.1,
            num_rays = 45,
            raysbeforedelay = 15,
            delaytime = 0.01,
            max_dist = 75,
            min_dist = 75,
            yaw = -70,
            pitch = 0,
            direction = -1,
            num_times = 3,
        },
        HeavySwing2 = {
            start = 0.1,
            num_rays = 30,
            raysbeforedelay = 15,
            delaytime = 0.01,
            max_dist = 50,
            min_dist = 25,
            yaw = -70,
            pitch = 0,
            direction = -1,
            num_times = 3,
        },
    },
    EquippedWalkspeedChange = 0,
    HolsteredWalkspeedChange = 0,
    EquippedWalkspeedMultiplier = 0,
    HolsteredWalkspeedMultiplier = 1.02,
    FirstDrawAnimation = nil,
    FirstDrawAnimationTime = nil,
    DrawAnimation = "Swing2",
    DrawAnimationTime = 1.5,
    KeyFrameSounds = {
        Slash = {SoundId = "18945906564", Volume = 1},
        Swing = {SoundId = "18945908955", Volume = 1},
        ChargeSlash1 = {SoundId = "5989940114", Volume = 1.5},
        ChargeSlash2 = {SoundId = "5160064829", Volume = 1.5},
        ChargeSlash3 = {SoundId = "5160064829", Volume = 1.5},
        Charge = {SoundId = "6839474791", Volume = 1.5},
    },
    UnequipSFX = {SoundId = "481731911", Volume = 0.5},
    DeploySFX = {SoundId = "5752235534", Volume = 0.5},
    HitSFX = {ID = "5989945551", PlaybackSpeed = 0.8},
    BlockSFX = {SoundId = "119580857539801", Volume = 0.5},
    StartBlockSFX = {SoundId = "9116844753", Volume = 0.5},
    NewSkinsSystem = false,
    NewSkinsSystemBlacklist = {},
    Parried = function(p1) -- Line: 192
        local Parry = p1.Viewmodel.Model.KeyParts.Parry
        Parry.ParrySparks:Emit(math.random(10, 25))
        Parry.Attachment.ParryLargeSparkParticles:Emit(1)
    end,
    Blocked = function(p1) -- Line: 198
        p1.Viewmodel.Model.KeyParts.Parry.ParrySparks:Emit(math.random(10, 25))
    end,
    DynamicFOVOffsetConstant = 3,
    Offset = CFrame.new(),
    SprintOffset = CFrame.new(),
    CrouchAnimation = CFrame.new(),
}
local v2 = CFrame.new(0, -1.7, 0)
v1.BlockOffset = v2 * CFrame.Angles(1.1423973285781066, 0, -1.5707963267948966)
v2 = CFrame.new(0, -2, 3)
v1.HolsterCF = v2 * CFrame.Angles(-0.4363323129985824, 0, 0)
v1.AttachmentNodeData = require("@game/ReplicatedStorage/common/SharedResources/Attachments/Platforms/BaseMelee")
return v1