local Red = require(game.ReplicatedStorage.Packages.Red)
local Guard = require(game.ReplicatedStorage.Packages.Guard)
local u15 = Guard.Or(Guard.Vector3, Guard.CFrame)
return Red.SharedSignalEvent("ForceTeleport", function(p1) -- Line: 6 -- upvalues: u15 (val)
    return u15(p1)
end)