local Red = require(game.ReplicatedStorage.Packages.Red)
local Guard = require(game.ReplicatedStorage.Packages.Guard)
local u18 = Guard.Or(Guard.Vector3, Guard.Or(Guard.Instance, Guard.String))
return Red.SharedEvent("LookAt", function(p1) -- Line: 6 -- upvalues: u18 (val)
    return u18(p1)
end)