local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Fusion = require(ReplicatedStorage.Packages.Fusion)
local New = Fusion.New
local Children = Fusion.Children
local Frame = New("Frame")
local v1 = {
    Name = "Header",
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    Size = UDim2.fromScale(1, 0.065),
}
local v2 = {}
local UICorner = New("UICorner")
local v3 = UICorner({Name = "UICorner", CornerRadius = UDim.new(0.3, 0)})
local TextLabel = New("TextLabel")
local v4 = TextLabel({
    Name = "TextLabel",
    BackgroundTransparency = 1,
    Text = "SETTINGS",
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
    AnchorPoint = Vector2.new(1, 0),
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
    Position = UDim2.fromScale(0.99, 0),
    Size = UDim2.fromScale(0.15, 1),
    TextColor3 = Color3.fromRGB(255, 184, 84),
})
local TextButton = New("TextButton")
local v5 = {
    Name = "Exit",
    Active = false,
    AnchorPoint = Vector2.new(1, 1),
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    LayoutOrder = 1000,
    Position = UDim2.new(1, 5, 0, -10),
    Size = UDim2.fromOffset(35, 35),
    Visible = false,
}
local v6 = {}
local ImageLabel = New("ImageLabel")
local v7 = {
    Name = "WeaponStats",
    AnchorPoint = Vector2.new(0.5, 0.5),
    BackgroundColor3 = Color3.fromRGB(248, 248, 248),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    Image = "rbxassetid://2851926732",
    ImageColor3 = Color3.fromRGB(255, 73, 73),
    LayoutOrder = -1,
    Position = UDim2.fromScale(0.5, 0.5),
    ScaleType = Enum.ScaleType.Slice,
    Selectable = true,
    Size = UDim2.fromScale(1, 1),
    SliceCenter = Rect.new(12, 12, 12, 12),
}
local v8 = {}
local ImageLabel_2 = New("ImageLabel")
local v9 = ImageLabel_2({
    Name = "Fill",
    BackgroundTransparency = 1,
    Image = "rbxassetid://2851928361",
    AnchorPoint = Vector2.new(0.5, 0.5),
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    ImageColor3 = Color3.fromRGB(49, 49, 49),
    Position = UDim2.fromScale(0.5, 0.5),
    ScaleType = Enum.ScaleType.Slice,
    Size = UDim2.new(1, -10, 1, -10),
    SliceCenter = Rect.new(7, 7, 7, 7),
})
local TextLabel_2 = New("TextLabel")
local v10 = {
    Name = "Label",
    AnchorPoint = Vector2.new(0.5, 0.5),
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
    Position = UDim2.fromScale(0.525, 0.5),
    Size = UDim2.fromScale(0.85, 0.8),
    Text = "X",
    TextColor3 = Color3.fromRGB(255, 73, 73),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
local v11 = {}
local UITextSizeConstraint = New("UITextSizeConstraint")
v11[1] = UITextSizeConstraint({Name = "UITextSizeConstraint", MaxTextSize = 20})
v10[Children] = v11
v8[1] = v9
v8[2] = TextLabel_2(v10)
v7[Children] = v8
v6[1] = ImageLabel(v7)
v5[Children] = v6
v2[1] = v3
v2[2] = v4
v2[3] = TextButton(v5)
v1[Children] = v2
return Frame(v1)