local v1 = {
    {
        Type = "Reward",
        RewardId = "THANKSGIVING2025_WIN15",
        RewardType = "Item",
        ItemId = "1327",
        Title = "Turkey Hunt Veteran",
        Requirement = "Win 15 Turkey Hunt matches as either a hunter or turkey.",
        RequiredCount = 15,
        TrackingId = "THANKSGIVING2025_WIN15",
    },
    {
        Type = "Reward",
        RewardId = "THANKSGIVING2025_KILL50",
        RewardType = "Item",
        ItemId = "1328",
        Title = "Featherweight Hunter",
        Requirement = "Eliminate 25 turkeys in Turkey Hunt.",
        RequiredCount = 25,
        TrackingId = "THANKSGIVING2025_KILL50",
    },
    {
        Type = "Reward",
        RewardId = "THANKSGIVING2025_KILL100",
        RewardType = "Item",
        ItemId = "2154",
        Title = "Seasoned Slayer",
        Requirement = "Eliminate 50 turkeys in Turkey Hunt.",
        RequiredCount = 50,
        TrackingId = "THANKSGIVING2025_KILL100",
    },
    {
        Type = "Reward",
        RewardId = "THANKSGIVING2025_SURVIVE15",
        RewardType = "Item",
        ItemId = "3109",
        Title = "Tenacious Turkey",
        Requirement = "Survive 15 Turkey Hunt rounds as a turkey.",
        RequiredCount = 15,
        TrackingId = "THANKSGIVING2025_SURVIVE15",
    },
    {
        Type = "Reward",
        RewardId = "THANKSGIVING2025_SURVIVE30",
        RewardType = "Item",
        ItemId = "3111",
        Title = "Seasoned Survivor",
        Requirement = "Survive 30 Turkey Hunt rounds as a turkey.",
        RequiredCount = 30,
        TrackingId = "THANKSGIVING2025_SURVIVE30",
    },
}
return {
    Id = "THANKSGIVING2025",
    DataStoreKey = "THANKSGIVING2025",
    Title = "Thanksgiving 2025",
    Description = "Hunt Turkeys or hide from Hunters in the new unique Turkey Hunt mode in Arcade. This event introduces new limited bundles, featured limited skins, and five event challenge rewards tied to your Turkey Hunt kills and wins stats.",
    StartTimestamp = 1763658000,
    EndTimestamp = 1765645200,
    ThumbnailImage = "rbxassetid://74106517311707",
    PurchaseableItems = {
        {
            Type = "Purchaseable",
            ItemId = "1329",
            DisplayName = "Sunpiercer ARK-3",
            Description = "Carve through the clouds with the Sunpiercer ARK-3. ZBucks only.",
            Currency = "ZBucks",
            Price = 20000,
        },
        {
            Type = "Purchaseable",
            ItemId = "2155",
            DisplayName = "Feathered Firepower MAC-10",
            Description = "Turn the MAC-10 into a holiday statement piece. ZBucks only.",
            Currency = "ZBucks",
            Price = 15000,
        },
        {
            Type = "Purchaseable",
            ItemId = "3110",
            DisplayName = "Quill-Pen Scimitar",
            Description = "This quill draws in steel. ZBucks only.",
            Currency = "ZBucks",
            Price = 10000,
        },
    },
    RewardItems = v1,
    Rewards = v1,
}