local v1 = {
    {
        Type = "Reward",
        RewardId = "EXTCH4_GOOD_ENDING",
        RewardType = "Item",
        ItemId = "1319",
        Title = "Black Snake's Worst Nightmare",
        Requirement = "Complete EXT CH4 on Hard difficulty with the good ending.",
        RequiredCount = 1,
        TrackingId = "EXTCH4_GOOD_ENDING",
    },
    {
        Type = "Reward",
        RewardId = "EXTCH4_GOOD_ENDING_NO_ABILITY",
        RewardType = "Item",
        ItemId = "1320",
        Title = "Resourceless",
        Requirement = "Complete EXT CH4 on Hard difficulty with the good ending and the NoAbility modifier.",
        RequiredCount = 1,
        TrackingId = "EXTCH4_GOOD_ENDING_NO_ABILITY",
    },
    {
        Type = "Reward",
        RewardId = "EXTCH4_GOOD_ENDING_SECONDARY_ONLY",
        RewardType = "Item",
        ItemId = "2153",
        Title = "Make every bullet count",
        Requirement = "Complete EXT CH4 on Hard difficulty with the good ending and the SecondaryOnly modifier.",
        RequiredCount = 1,
        TrackingId = "EXTCH4_GOOD_ENDING_SECONDARY_ONLY",
    },
    {
        Type = "Reward",
        RewardId = "EXTCH4_GOOD_ENDING_MELEE_ONLY",
        RewardType = "Item",
        ItemId = "3106",
        Title = "Pointy Objects",
        Requirement = "Complete EXT CH4 on any difficulty with the good ending and the MeleeOnly modifier.",
        RequiredCount = 1,
        TrackingId = "EXTCH4_GOOD_ENDING_MELEE_ONLY",
    },
    {
        Type = "Reward",
        RewardId = "ZTWR_SPEEDRUN",
        RewardType = "Item",
        ItemId = "1322",
        Title = "Energetic Zombies",
        Requirement = "Complete 20 Floors on Hard difficulty with SuperQuickAttackZombies and UsainBoltZombies modifiers.",
        RequiredCount = 1,
        TrackingId = "ZTWR_SPEEDRUN",
    },
    {
        Type = "Reward",
        RewardId = "ZTWR_PLAYTHROUGH",
        RewardType = "Item",
        ItemId = "4038",
        Title = "Happy Halloween!",
        Requirement = "Complete 20 Floors or No Mercy on any difficulty. No modifiers required.",
        RequiredCount = 1,
        TrackingId = "ZTWR_PLAYTHROUGH",
    },
    {
        Type = "Reward",
        RewardId = "ZTWR_ELITE_CHALLENGE",
        RewardType = "Item",
        ItemId = "3107",
        Title = "Few Are Destined...",
        Requirement = "Complete 20 Floors on Hard difficulty with TripleZombies, TankyZombies, NoDowns, Quintuple Damage, and ExplodingZombies modifiers.",
        RequiredCount = 1,
        TrackingId = "ZTWR_ELITE_CHALLENGE",
    },
    {
        Type = "Reward",
        RewardId = "NOMERCY_ROUND20_SECONDARY_ONLY",
        RewardType = "Item",
        ItemId = "2151",
        Title = "Blazing Skull",
        Requirement = "Complete 20 waves or more in No Mercy on Hard difficulty with SecondaryOnly, GunsBlazing, PlayersRunFaster, and EverythingOneShots modifiers.",
        RequiredCount = 1,
        TrackingId = "NOMERCY_ROUND20_SECONDARY_ONLY",
    },
}
return {
    Id = "EXTCH4HALLOWEEN",
    DataStoreKey = "EXTCH4HALLOWEEN",
    Title = "EXT CH4 & Halloween Event",
    Description = "Celebrate the Halloween season with Extraction Chapter 4 challenges and spooky rewards.",
    StartTimestamp = 1761948000,
    EndTimestamp = 1763834400,
    ThumbnailImage = "rbxassetid://71420230245201",
    PurchaseableItems = {
        {
            Type = "Purchaseable",
            ItemId = "2150",
            DisplayName = "MLT-18",
            Description = "Limited-time MLT-18 variant available during the EXT CH4 Halloween event.",
            Currency = "ZBucks",
            Price = 10000,
        },
        {
            Type = "Purchaseable",
            ItemId = "1321",
            DisplayName = "Witch Stalker M1014",
            Description = "Haunted shotgun skin with a spellbinding finish.",
            Currency = "ZBucks",
            Price = 15000,
        },
        {
            Type = "Purchaseable",
            ItemId = "2152",
            DisplayName = "Phantomstone CZ 75",
            Description = "Phantomstone sidearm wrapped in spectral energy.",
            Currency = "ZBucks",
            Price = 7500,
        },
    },
    RewardItems = v1,
    Rewards = v1,
}