return {
    Ammo = 3,
    StoredAmmo = 42,
    AmmoType = nil,
    Damage = 18,
    Multipliers = {Arms = 1, Torso = 1, Legs = 1, Head = 1.85},
    Penetration = 0,
    PenetrationReduction = 0.5,
    DamageDropoff = {
        {Distance = 10, Damage = 17},
        {Distance = 50, Damage = 8},
        {Distance = 50, Damage = 3},
        {Distance = 100, Damage = 5},
    },
    FireMode = {"Pump Action"},
    DelayPerShot = 0.5,
    PrimeAction = true,
    BoltAnimationTime = 1.2,
    BurstAmt = nil,
    BurstDelay = nil,
    ADSSpeed = 1.3,
    DrawSpeed = 1.3,
    HolsterSpeed = 1.3,
    BulletsPerShot = 12,
    UsesLoadLoop = true,
    ShouldNotCycleAfterReload = true,
    LoadStartEmptyAnimationTime = 1.8,
    LoadStartEmptyTime = 1.8,
    LoadStartEmptyInsertTime = 0.8,
    LoadStartAnimationTime = 0.5,
    LoadStartTime = 0.5,
    LoadStopAnimationTime = 0.5,
    LoadStopTime = 0.5,
    InsertTime = 0.4,
    IncrAmmoCountTime = 0.1,
    EquippedWalkspeedChange = 0,
    HolsteredWalkspeedChange = 0,
    EquippedWalkspeedMultiplier = 0.95,
    HolsteredWalkspeedMultiplier = 1,
    BaseSpread = 0.3141592653589793,
    CrouchSpreadReduction = nil,
    ProneSpreadReduction = nil,
    ADSSpreadReduction = 0.65,
    MovementSpread = nil,
    AirSpread = nil,
    SlidingSpread = nil,
    DivingSpread = nil,
    ShootingSpreadIncrement = nil,
    ShootingSpreadDecay = nil,
    FirstDrawAnimation = nil,
    FirstDrawAnimationTime = nil,
    DrawAnimation = nil,
    DrawAnimationTime = nil,
    ShootSingle = {SoundId = "6839481031", Volume = 0.25},
    SuppressorShootSingle = {SoundId = "9325905648", Volume = 1.2},
    AutoLoop = nil,
    AutoLoopTail = nil,
    KeyFrameSounds = {
        pump_back = {SoundId = "3299747822", Volume = 0.5},
        e_back = {SoundId = "4993319040", Volume = 0.5},
        e_forward = {SoundId = "4993319579", Volume = 0.5},
        ins_shell = {SoundId = "6001410744", Volume = 0.5},
    },
    DeploySFX = nil,
    ShellOn = "pump_back",
    IsAPistol = true,
    UsePistolIcon = false,
    BulletCasing = "shotgun",
    WorldScaleValue = 0.9,
    NewSkinsSystem = false,
    NewSkinsSystemBlacklist = {},
    IsShotgun = true,
    DynamicFOVOffsetConstant = 3,
    AimDynamicFOVOffsetConstant = -0.5,
    Offset = CFrame.new(0, 0, 0),
    SprintOffset = (CFrame.new(0.2, 0.3, -0.25)) * CFrame.Angles(-0.5, 0.3, 0.1),
    AimOffset = CFrame.new(0.563085556, -0.08, 0.3),
    VerticalRecoil = 18.52,
    HorizontalRecoil = 19,
    AttachmentNodeData = require("@game/ReplicatedStorage/common/SharedResources/Attachments/Platforms/BaseShotgun"),
}