return {
    Riser = {
        ID = "MI0",
        UnlockLevel = 0,
        Image = "rbxassetid://13833356972",
        Description = "Rises the sightline",
        Pros = {"Height"},
    },
    ["Red Laser"] = {
        ID = "MI1",
        UnlockLevel = 5,
        Image = "rbxassetid://13833356524",
        Description = "Reduces hipfire spread.",
        Pros = {"Reduced hipfire spread"},
    },
    ["Green Laser"] = {
        ID = "MI2",
        UnlockLevel = 9,
        Image = "rbxassetid://13833356524",
        Description = "Reduces hipfire spread.",
        Pros = {"Reduced hipfire spread [30%]"},
        Cons = {"Reduced Aim Spread [33%]"},
    },
    ["Orange Laser"] = {
        ID = "MI3",
        UnlockLevel = 10,
        Image = "rbxassetid://13833356524",
        Description = "Reduces hipfire spread.",
        Pros = {"Reduced hipfire spread [30%]"},
        Cons = {"Reduced Aim Spread [33%]"},
    },
    ["Small Flashlight"] = {
        ID = "MI4",
        UnlockLevel = 12,
        Image = "rbxassetid://13833357251",
        Description = "Provides illumination.",
        Pros = {"Illumination"},
    },
    ["Point Aim"] = {
        ID = "MI5",
        UnlockLevel = 20,
        Image = "rbxassetid://13833357251",
        Description = "Provides lasers.",
        Pros = {"Increased ADS Spread Reduction [40%]", "Enables point-aim when no optics are equipped"},
        Cons = {"Increased Base Spread [20%]", "Laser may be difficult to see"},
    },
}