return {
    Graphics = {
        QualityTier = "Auto",
        Ragdolls = true,
        Flinching = true,
        HeadgearHeadshot = false,
        BulletHoles = true,
        ArmorDestroyEffect = true,
        ZombieQuality = 4,
        ParticleQuality = 4,
        BaseFOV = 70,
        AnimatedTextures = true,
        RagdollTimer = 4,
        BulletTracers = true,
        BulletShells = true,
        HideNearbyPlayers = false,
        ShowMeleeHitboxes = false,
        DisplayDamageIndicators = false,
        ProceduralAnimations = true,
    },
    Sound = {RagdollSounds = true, MusicVolume = 1, MainMenuTheme = (require("./MainMenuThemes")).Ambience},
    Meta = {SettingsMigration = 0},
    MainMenu = {TradeEnabled = true, ShowLevel = true, ShowStats = true},
    Camera = {MaxCameraDistance = 6, ThirdPersonSide = 1, PinchToZoom = true, ScrollWheelZoom = true},
    Controls = {
        Sensitivity = 1,
        AimingSensitivity = 1,
        AutoShoot = true,
        AutoJump = false,
        DPadSelection = false,
        ShowEditButton = false,
        DynamicStaminaUI = true,
        MobileSelectionMode = 1,
        GamepadSelectionMode = 1,
        ShowControlHints = true,
        HotbarScale = 0.95,
        Binds = {
            Reload = {Keyboard = Enum.KeyCode.R, Gamepad = Enum.KeyCode.ButtonX},
            PrimaryAttack = {Mouse = Enum.UserInputType.MouseButton1, Gamepad = Enum.KeyCode.ButtonR2},
            SecondaryAttack = {Mouse = Enum.UserInputType.MouseButton2, Gamepad = Enum.KeyCode.ButtonL2},
            ToggleSecondaryAttack = {Keyboard = Enum.KeyCode.Q},
            Firemode = {Keyboard = Enum.KeyCode.B, Gamepad = Enum.KeyCode.ButtonY},
            QuickMeleeAndBlock = {Keyboard = Enum.KeyCode.V},
            OffHandUse = {Keyboard = Enum.KeyCode.F, Gamepad = Enum.KeyCode.ButtonR1},
            SprintHold = {Keyboard = Enum.KeyCode.LeftShift},
            SprintToggle = {Gamepad = Enum.KeyCode.ButtonL3},
            CrouchHold = {Keyboard = Enum.KeyCode.LeftControl},
            CrouchToggle = {Keyboard = Enum.KeyCode.C},
            ProneToggle = {Keyboard = Enum.KeyCode.X},
            CrouchProneToggle = {Gamepad = Enum.KeyCode.ButtonB},
            ToggleControlHints = {Keyboard = Enum.KeyCode.H},
            Thirdperson = {Keyboard = Enum.KeyCode.Z, Gamepad = Enum.KeyCode.ButtonR3},
            PromptInteract = {Keyboard = Enum.KeyCode.E, Gamepad = Enum.KeyCode.ButtonX},
            LeaderboardToggle = {},
            LeaderboardHold = {Keyboard = Enum.KeyCode.Tab},
            NVGToggle = {Keyboard = Enum.KeyCode.N, Gamepad = Enum.KeyCode.ButtonL1},
            QuickChat = {Keyboard = Enum.KeyCode.G},
        },
    },
}