local Fusion = require(game.ReplicatedStorage.Packages.Fusion)
local v1 = Fusion.scoped(Fusion)
local Children = Fusion.Children
local v2 = v1:New("ScreenGui")
local v3 = {
    Name = "Edit",
    IgnoreGuiInset = true,
    ScreenInsets = Enum.ScreenInsets.DeviceSafeInsets,
    ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
}
local v4 = {}
local v5 = v1:New("Frame")
local v6 = {
    Name = "Frame",
    AnchorPoint = Vector2.new(0.5, 0),
    BackgroundColor3 = Color3.fromRGB(1, 21, 40),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    BorderSizePixel = 0,
    ClipsDescendants = true,
    Position = UDim2.fromScale(0.5, 0),
    Size = UDim2.fromOffset(405, 0),
}
local v7 = {}
local v8 = v1:New("TextLabel")({
    Name = "TextLabel",
    BackgroundTransparency = 1,
    Text = "Tap on a button to edit",
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
    AnchorPoint = Vector2.new(0.5, 0),
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    FontFace = Font.new("rbxasset://fonts/families/Nunito.json"),
    Position = UDim2.fromScale(0.5, 0),
    Size = UDim2.fromOffset(364, 50),
    TextColor3 = Color3.fromRGB(255, 255, 255),
})
local v9 = v1:New("TextButton")
local v10 = {
    Name = "Save",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(31, 207, 0),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(26, 122, 0),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(202, 100),
    Size = UDim2.fromOffset(102, 50),
    Text = "Save",
    TextColor3 = Color3.fromRGB(0, 0, 0),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v10[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 22})}
v9 = v9(v10)
v10 = v1:New("TextButton")({
    Name = "Dec",
    BackgroundTransparency = 0.75,
    BorderSizePixel = 5,
    Text = "-",
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(75, 104, 139),
    BorderColor3 = Color3.fromRGB(66, 92, 122),
    BorderMode = Enum.BorderMode.Inset,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(101, 100),
    Size = UDim2.fromOffset(101, 50),
    TextColor3 = Color3.fromRGB(0, 0, 0),
})
local v11 = v1:New("TextButton")
local v12 = {
    Name = "Cancel",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(188, 0, 0),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(122, 0, 0),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(304, 100),
    Size = UDim2.fromOffset(102, 50),
    Text = "Cancel",
    TextColor3 = Color3.fromRGB(0, 0, 0),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v12[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 22})}
v11 = v11(v12)
v12 = v1:New("TextButton")({
    Name = "Incr",
    BackgroundTransparency = 0.75,
    BorderSizePixel = 5,
    Text = "+",
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(75, 104, 139),
    BorderColor3 = Color3.fromRGB(66, 92, 122),
    BorderMode = Enum.BorderMode.Inset,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(0, 100),
    Size = UDim2.fromOffset(101, 50),
    TextColor3 = Color3.fromRGB(0, 0, 0),
})
local v13 = v1:New("TextButton")
local v14 = {
    Name = "Reset",
    AnchorPoint = Vector2.new(0.5, 1),
    BackgroundColor3 = Color3.fromRGB(188, 94, 0),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(122, 81, 0),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.new(0.5, 0, 0, 150),
    Size = UDim2.fromOffset(102, 50),
    Text = "Reset",
    TextColor3 = Color3.fromRGB(0, 0, 0),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v14[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 22})}
v13 = v13(v14)
v14 = v1:New("Frame")
local v15 = {
    Name = "Frame",
    BackgroundTransparency = 0.25,
    BorderSizePixel = 0,
    ZIndex = 0,
    BackgroundColor3 = Color3.fromRGB(1, 21, 40),
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    Size = UDim2.fromOffset(405, 50),
}
v7[1] = v8
v7[2] = v9
v7[3] = v10
v7[4] = v11
v7[5] = v12
v7[6] = v13
v7[7] = v14(v15)
v6[Children] = v7
v5 = v5(v6)
v6 = v1:New("Frame")
v7 = {
    Name = "Options",
    AnchorPoint = Vector2.new(0.5, 0),
    BackgroundColor3 = Color3.fromRGB(1, 21, 40),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    BorderSizePixel = 0,
    ClipsDescendants = true,
    Position = UDim2.new(0.5, 0, 0, 50),
    Size = UDim2.fromOffset(306, 0),
}
v8 = {}
v9 = v1:New("TextButton")
v10 = {
    Name = "Save",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(18, 188, 0),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(13, 138, 0),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(0, 50),
    Size = UDim2.fromOffset(102, 50),
    Text = "Save",
    TextColor3 = Color3.fromRGB(0, 0, 0),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v10[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 22})}
v9 = v9(v10)
v10 = v1:New("TextButton")
v11 = {
    Name = "Cancel",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(188, 0, 0),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(122, 0, 0),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(102, 50),
    Size = UDim2.fromOffset(102, 50),
    Text = "Cancel",
    TextColor3 = Color3.fromRGB(0, 0, 0),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v11[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 22})}
v10 = v10(v11)
v11 = v1:New("TextButton")
v12 = {
    Name = "Reset",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(188, 94, 0),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(122, 81, 0),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(204, 50),
    Size = UDim2.fromOffset(102, 50),
    Text = "Reset",
    TextColor3 = Color3.fromRGB(0, 0, 0),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v12[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 22})}
v8[1] = v9
v8[2] = v10
v8[3] = v11(v12)
v7[Children] = v8
v6 = v6(v7)
v7 = v1:New("Frame")
v8 = {
    Name = "Presets",
    AnchorPoint = Vector2.new(0.5, 0),
    BackgroundColor3 = Color3.fromRGB(1, 21, 40),
    BackgroundTransparency = 1,
    BorderColor3 = Color3.fromRGB(27, 42, 53),
    BorderSizePixel = 0,
    ClipsDescendants = true,
    Position = UDim2.new(0.5, 0, 0, 100),
    Size = UDim2.fromOffset(306, 0),
}
v9 = {}
v10 = v1:New("TextLabel")
v11 = {
    Name = "HintLabel",
    AnchorPoint = Vector2.new(0.5, 0),
    BackgroundTransparency = 1,
    FontFace = Font.new("rbxasset://fonts/families/Nunito.json"),
    Position = UDim2.fromScale(0.5, 0),
    Size = UDim2.fromOffset(306, 20),
    Text = "Hold to save preset, tap to load",
    TextColor3 = Color3.fromRGB(180, 180, 180),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v11[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 14})}
v10 = v10(v11)
v11 = v1:New("TextButton")
v12 = {
    Name = "Preset1",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(75, 104, 139),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(66, 92, 122),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(0, 70),
    Size = UDim2.fromOffset(102, 50),
    Text = "Preset 1",
    TextColor3 = Color3.fromRGB(255, 255, 255),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v12[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 18})}
v11 = v11(v12)
v12 = v1:New("TextButton")
v13 = {
    Name = "Preset2",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(75, 104, 139),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(66, 92, 122),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(102, 70),
    Size = UDim2.fromOffset(102, 50),
    Text = "Preset 2",
    TextColor3 = Color3.fromRGB(255, 255, 255),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v13[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 18})}
v12 = v12(v13)
v13 = v1:New("TextButton")
v14 = {
    Name = "Preset3",
    AnchorPoint = Vector2.new(0, 1),
    BackgroundColor3 = Color3.fromRGB(75, 104, 139),
    BackgroundTransparency = 0.75,
    BorderColor3 = Color3.fromRGB(66, 92, 122),
    BorderMode = Enum.BorderMode.Inset,
    BorderSizePixel = 5,
    FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json"),
    Position = UDim2.fromOffset(204, 70),
    Size = UDim2.fromOffset(102, 50),
    Text = "Preset 3",
    TextColor3 = Color3.fromRGB(255, 255, 255),
    TextScaled = true,
    TextSize = 14,
    TextWrapped = true,
}
v14[Children] = {v1:New("UITextSizeConstraint")({Name = "UITextSizeConstraint", MaxTextSize = 18})}
v9[1] = v10
v9[2] = v11
v9[3] = v12
v9[4] = v13(v14)
v8[Children] = v9
v4[1] = v5
v4[2] = v6
v4[3] = v7(v8)
v3[Children] = v4
return v2(v3)