local Red = require(game.ReplicatedStorage.Packages.Red)
local Guard = require(game.ReplicatedStorage.Packages.Guard)
return Red.Event("ChunkReceived", function(p1) -- Line: 4 -- upvalues: Guard (val)
    return Guard.Instance(p1)
end)